### ISSUE TITLE
A little problem on require "getbytes"

### ISSUE THREAD

**Issue by fengceqian** [jpbro/VbFcgi#14]
### EXPECTED BEHAVIOUR
Dear Sir,
I'm glad to share your Vbfcgi project code, which is written very well.
I found a problem in testing. I hope you can look at it. When requiring "getbytes", the first response is OK, the second times will be error , and the third is OK.
for example:
Http://127.0.0.1/vbfcgiapp.fcg? Getbytes=Rs --OK
Http://127.0.0.1/vbfcgiapp.fcg?Getbytes=Rs--Timeout
Http://127.0.0.1/vbfcgiapp.fcg? Getbytes=Rs --OK
Http://127.0.0.1/vbfcgiapp.fcg?Download=Rs--Timeout
Can you fix it? Thank you very much for sharing your code.
Best Regards
Fengce From China

**Comment by jpbro** [comment]
Hi Fengce! I'm really sorry for the delay on this - I've been away for the better part of a month helping a family member who was in the hospital.

I think I've been able to fix the problem in commit https://github.com/jpbro/VbFcgi/commit/5237402c3449820038cd548be6526b0be3ef7a97

Thank you very much for reporting the problem!
