### ISSUE TITLE
a bug about  po_Response.WriteBytes

### ISSUE THREAD

**Issue by fengceqian** [jpbro/VbFcgi#15]
It's my code. I found if the array size <10000,the client side can receive all bytes,If array size=100000,sometimes client side can receive whole bytes sometimes not.but if array size>20000000 never receive whole bytes.

Private Sub IFcgiApp_ProcessRequest(po_Request As VbFcgiLib.CFcgiRequest, _
                                    po_Response As VbFcgiLib.CFcgiResponse)
        '<EhHeader>
        On Error GoTo IFcgiApp_ProcessRequest_Err
        '</EhHeader>
 
        Dim ii           As Long
 
        Dim lo_Cnn       As vbRichClient5.cConnection

        Dim lo_Cmd       As vbRichClient5.cCommand

        Dim lo_Rs        As vbRichClient5.cRecordset
    
        Dim lo_Html      As VbFcgiLib.CBuilderHtml
    
        Dim lo_IBuilder  As VbFcgiLib.IBuilder
     
   
        Dim la_Content() As Byte
    
        Dim strSQL       As String
     
100     Set mo_FcgiParams = po_Request.Fcgi.Params
102     Set mo_HttpParams = po_Request.Http.QueryParameters
104     Set mo_FcgiStdin = po_Request.Fcgi.Stdin

106     If po_Request.Http.QueryParameters.Exists("ID") Then

108         Select Case po_Request.Http.QueryParameters("ID")
        
                Case "1"
                    ' Create an in-memory database
110                 Set lo_Cnn = libRc5Factory.C.Connection(, DBCreateInMemory)
112                 lo_Cnn.Execute "CREATE TABLE mytable (code TEXT, value1 INTEGER, value2 INTEGER, value3 REAL)"

                    ' Build random table data
114                 Set lo_Cmd = lo_Cnn.CreateCommand("INSERT INTO mytable (code, value1, value2, value3) VALUES (?,?,?,?)")

116                 For ii = 0 To 1000

118                     With lo_Cmd
120                         .SetAllParamsNull

122                         .SetText 1, Chr$(65)
124                         .SetInt32 2, Int(Rnd * 100)
126                         .SetInt32 3, Int(Rnd * 100)
128                         .SetDouble 4, Rnd

130                         .Execute

                        End With

132                 Next ii

                    ' Get data into recordset
134                 Set lo_Rs = lo_Cnn.OpenRecordset("SELECT * FROM mytable")
       
136                 la_Content = lo_Rs.Content
                
138                 po_Response.WriteBytes stringVbToUtf8("Content-Length: " & arraySize(la_Content) & vbNewLine)
140                 po_Response.WriteBytes stringVbToUtf8("Content-Type: application/octet-stream" & vbNewLine)
142                 po_Response.WriteBytes stringVbToUtf8("Content-Type: application/octet-stream" & vbNewLine)
144                 po_Response.WriteBytes stringVbToUtf8(vbNewLine)
146                 po_Response.WriteBytes la_Content
                
148                 Set lo_Cnn = Nothing
150                 Set lo_Rs = Nothing
152                 Set lo_Cmd = Nothing
154                 Erase la_Content
                
156             Case "2"
           
158                 Set lo_Cnn = libRc5Factory.C.Connection(, DBCreateInMemory)
160                 lo_Cnn.Execute "CREATE TABLE mytable (code TEXT, value1 INTEGER, value2 INTEGER, value3 REAL)"

                    ' Build random table data
162                 Set lo_Cmd = lo_Cnn.CreateCommand("INSERT INTO mytable (code, value1, value2, value3) VALUES (?,?,?,?)")

164                 For ii = 0 To 400000

166                     With lo_Cmd
168                         .SetAllParamsNull

170                         .SetText 1, Chr$(65)
172                         .SetInt32 2, Int(Rnd * 100)
174                         .SetInt32 3, Int(Rnd * 100)
176                         .SetDouble 4, Rnd

178                         .Execute

                        End With

180                 Next ii

                    ' Get data into recordset
182                 Set lo_Rs = lo_Cnn.OpenRecordset("SELECT * FROM mytable")
       
184                 la_Content = lo_Rs.Content
                
186                 po_Response.WriteBytes stringVbToUtf8("Content-Length: " & arraySize(la_Content) & vbNewLine)
188                 po_Response.WriteBytes stringVbToUtf8("Content-Type: application/octet-stream" & vbNewLine)
190                 po_Response.WriteBytes stringVbToUtf8("Content-Type: application/octet-stream" & vbNewLine)
192                 po_Response.WriteBytes stringVbToUtf8(vbNewLine)
194                 po_Response.WriteBytes la_Content
                
196                 Set lo_Cnn = Nothing
198                 Set lo_Rs = Nothing
200                 Set lo_Cmd = Nothing
202                 Erase la_Content

204             Case "3"
206                 Set lo_Cnn = libRc5Factory.C.Connection(, DBCreateInMemory)
208                 lo_Cnn.Execute "CREATE TABLE mytable (code TEXT, value1 INTEGER, value2 INTEGER, value3 REAL)"

                    ' Build random table data
210                 Set lo_Cmd = lo_Cnn.CreateCommand("INSERT INTO mytable (code, value1, value2, value3) VALUES (?,?,?,?)")

212                 For ii = 0 To 1000000

214                     With lo_Cmd
216                         .SetAllParamsNull

218                         .SetText 1, Chr$(65)
220                         .SetInt32 2, Int(Rnd * 100)
222                         .SetInt32 3, Int(Rnd * 100)
224                         .SetDouble 4, Rnd

226                         .Execute

                        End With

228                 Next ii

                    ' Get data into recordset
230                 Set lo_Rs = lo_Cnn.OpenRecordset("SELECT * FROM mytable")
       
232                 la_Content = lo_Rs.Content
                
234                 po_Response.WriteBytes stringVbToUtf8("Content-Length: " & arraySize(la_Content) & vbNewLine)
236                 po_Response.WriteBytes stringVbToUtf8("Content-Type: application/octet-stream" & vbNewLine)
238                 po_Response.WriteBytes stringVbToUtf8("Content-Type: application/octet-stream" & vbNewLine)
240                 po_Response.WriteBytes stringVbToUtf8(vbNewLine)
242                 po_Response.WriteBytes la_Content
                
244                 Set lo_Cnn = Nothing
246                 Set lo_Rs = Nothing
248                 Set lo_Cmd = Nothing
250                 Erase la_Content

            End Select

        End If

Cleanup:

        On Error GoTo ErrorHandler
         
        ' Check if we remembered to call Finish() on the IBuilder object (if set)
252     If Not lo_IBuilder Is Nothing Then
254         If Not lo_IBuilder.IsFinished Then
                ' We forgot to call Finish()!
                ' Call Finish with the recommended default
                ' content encoding of the IBuilder helper class.
256             lo_IBuilder.Finish

            End If

        End If

258     Cleanup

        Exit Sub

ErrorHandler:

        Dim l_ErrNum  As Long

        Dim l_ErrDesc As String

260     l_ErrNum = Err.Number
262     l_ErrDesc = Err.Description & ", Line #" & Erl

264     Cleanup

        ' Send error information downstream
266     po_Response.Error l_ErrNum, l_ErrDesc

        '<EhFooter>
        Exit Sub

IFcgiApp_ProcessRequest_Err:
        MsgBox Err.Description & vbCrLf & _
               "in TestRs.CFcgiApp.IFcgiApp_ProcessRequest " & _
               "at line " & Erl, _
               vbExclamation + vbOKOnly, "Application Error"
        Resume Next
        '</EhFooter>
End Sub

**Comment by jpbro** [comment]
Hi @fengceqian, thanks for submitting this issue and for providing sample code.

I've tested out your code, and part of the problem is that the you aren't calling the Finished method on the po_Response object. My demo app has a test for this at the end by checking if Finish has been called on the IBuilder object, but you aren't setting the lo_Builder variable to an IBuilder object, so this check doesn't do anything.

I recommend calling po_Response.Finished when you are done building your response. You can also use the following code in the Cleanup section of the IFcgiApp_ProcessRequest method to work as a better fail-safe for when you forget to call the Finished method:

`   If Not po_Response Is Nothing Then
`      If Not po_Response.IsFinished Then
`         ' We forgot to call Finish()!
`         ' Call Finished with the recommended default
`         ' content encoding of the IBuilder helper class.
`         
`         po_Response.Finished
`
`      End If
`   End If

If the problem persists after making the above changes, please make sure you are using the latest version of the VbFcgi library as I made some fixes to the response code here: https://github.com/jpbro/VbFcgi/issues/14

**Comment by fengceqian** [comment]
I am very glad to get your reply.I know how to fix my program. Thank you very much. by the way ,did your receive the code of nginx console write by DOS.
